[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://aujguzeejukhopajxbqe.supabase.co"
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_zXJoMwUnzF2O4qNh4iw8wg_b9UgLfha"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
